#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ $USER = "root" ]

mkdir -p "$logdir" "$datadir" "$datadir/counters"
chown www-data:www-data "$logdir" "$datadir" "$datadir/counters" -R

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R


### RENAME FETCH CGI ###
cd "$appdir"
#rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
#[ -e "/home/fuji/rnd" ] && rand="$(cat /home/fuji/rnd )"  # REMOVE LATER

# mv "fetch" "fetch_$rnd.cgi"
mv "fetch" "fetch.cgi"

### PULL ARTICLE REPO ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents.git"

chown www-data:www-data "$contentsdir" -R

#echo "call fetch_$rnd.cgi from GitHub"

